name: GitHub YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "15 21 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: ProjectSoft-STUDIONIONS/ProjectSoft-STUDIONIONS@main
        with:
          channel_id: UCCetHlZWSx1FJRlZ6JgWzmQ
          comment_tag_name: EXAMPLE-YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
          theme_context_light: '{ "background_color": "#ffffff", "title_color": "#24292f", "stats_color": "#57606a" }'
          theme_context_dark: '{ "background_color": "#0d1117", "title_color": "#ffffff", "stats_color": "#dedede" }'
          max_title_lines: 10
          output_type: html
